# Generated by Django 4.2.8 on 2023-12-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendor_system", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Completed", "Completed"),
                    ("Canceled", "Canceled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
